"""fixed task-tag relationship part 4

Revision ID: 16b2467a0f62
Revises: 679508f97d99
Create Date: 2024-04-16 19:33:36.181841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b2467a0f62'
down_revision: Union[str, None] = '679508f97d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('association_table', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('association_table', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('association_table', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('association_table', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
