"""fixed task-tag relationship part 3

Revision ID: 679508f97d99
Revises: 3c43d7b35bd5
Create Date: 2024-04-16 14:06:28.451209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '679508f97d99'
down_revision: Union[str, None] = '3c43d7b35bd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_table',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], )
    )
    op.drop_table('task_tag_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_tag_association',
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='task_tag_association_tag_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='task_tag_association_task_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tag_id', 'task_id', name='task_tag_association_pkey')
    )
    op.drop_table('association_table')
    # ### end Alembic commands ###
